# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing these this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: Ramkumar K R
email: ramkumarkr@outlook.in
description: > # this means to ignore newlines until "baseurl:"
  Every developer has his/her blog. This one is mine.
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://ramkumar-kr.github.io" # the base hostname & protocol for your site
twitter_username: ramkumarkr94
github_username: ramkumar-kr
logo: https://avatars3.githubusercontent.com/u/4789010?v=3&s=460

highlighter: 'rouge'

# Build settings
markdown: kramdown
theme: minima
include: ["_pages"]
collections:
  showcases:
    output: true

plugins:
  - jekyll-sitemap

